#!/usr/bin/env python2
import cv2
import sys

imgs = ((cv2.cvtColor(cv2.imread(name), cv2.COLOR_HSV2BGR), name)
        for name in sys.argv[1:])

for img, name in imgs:
    cv2.imshow(name, img)

cv2.waitKey()
cv2.destroyAllWindows()
